### ISSUE TITLE
Can't control VLC after switching to next track in playlist

### ISSUE THREAD

**Issue by dreua** [icasdri/mpris2controller#12]
Hey, first of all thanks for the great tool! (I think this mpris2controller-like behavior should become built into DEs like Gnome, but that is another issue...)

It works great for me except with VLC-Playlists, does someone have the same issue or could give guidance on how to debug and fix this?

### Steps to reproduce
1. Load a playlist with two tracks (Just open two files, I use webm videos)
2. Wait for VLC to automatically switch to the next track, use VLCs "next" button or `mpris2controller Next`, it does not matter.
3. Try to PlayPause VLC

### Expected results
`mpris2controller PlayPause` works as usual

### Actual results
`mpris2controller PlayPause` has no effect in most cases (it works once after 4 "Next" iterations)

### Additional information
```
[da@David-UB ~]$ mpris2controller Next # Works always!
[da@David-UB ~]$ mpris2controller PlayPause # No effect
[da@David-UB ~]$ mpris2controller Status # Correct
Playing
[da@David-UB ~]$ mpris2controller Metadata # Correct
{"mpris:trackid": "/org/videolan/vlc/playlist/3", "xesam:url": "file:///home/da/Downloads/[...].webm", "vlc:time": 250, "mpris:length": 250440992, "vlc:length": 250440, "vlc:publisher": 5}
```

Just pressing Pause in VLC once fixes this for the current track.

**Versions:**
- VLC 3.0.11.1
- Fedora 32
- mpris2controller 0.9

**Comment by icasdri** [comment]
Does this only occur with VLC playlists or anything played in VLC?

And, can you attach debug output?
1. Stop all running daemons `mpris2controller Quit`
2. Manaully start daemon in foreground with debug output `mpris2controller --nofork --debug`
3. In another terminal, use `mpris2controller --debug PlayPause`, etc.

**Comment by dreua** [comment]
> Does this only occur with VLC playlists or anything played in VLC?

As I understand it, VLC always creates an ad hoc playlist: I tried with a very short video and VLC put that in the playlist and repeated after it was finished (not sure if that is some setting). Anyway, it occurs exactly the same when playing one video on repeat.

First of all thanks for the debugging instructions!

[Full commented log](https://github.com/icasdri/mpris2controller/files/6643326/2021-06-13-vlc-mpris.log)

Output of 3. is always the same:
```
$ mpris2controller --debug PlayPause
Daemon already running.
Calling method PlayPause on daemon.
```

Depending on how fast / often I click next in VLC, the player status is sometimes incorrectly reported as not playing:
```
PlaybackStatus PropertiesChanged from :1.1309.
:1.1309 marked as not playing.
```
Not sure whether this is a bug in VLC or how we can debug this further. (Maybe a race condition between the Pause and the following Play event?)

News: I just tested the built-in Play/Pause support of a more recent Gnome and realized that it implements mpris2controller like features (it doesn't in older versions): It even works with VLC and I'm happy with it so far, therefore I'm not interested in solving this issue for my own usage any more but I'll help you in case you want to fix it anyway. (In that case just reopen and let me know what you need.)
